/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GREAT = 4;
  /** RegularExpression Id. */
  int LESS = 5;
  /** RegularExpression Id. */
  int GREATGREAT = 6;
  /** RegularExpression Id. */
  int GREATAMPERSAND = 7;
  /** RegularExpression Id. */
  int PIPE = 8;
  /** RegularExpression Id. */
  int AMPERSAND = 9;
  /** RegularExpression Id. */
  int EOL = 10;
  /** RegularExpression Id. */
  int WORD = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\">\"",
    "\"<\"",
    "\">>\"",
    "\">&\"",
    "\"|\"",
    "\"&\"",
    "\"\\n\"",
    "<WORD>",
  };

}
